### ISSUE TITLE
eMMC brick bug の詳細について

### ISSUE THREAD

**Issue by coosee** [kbc-developers/android_kernel_samsung_msm8660-common#2]
ここではeMMC brick bug の詳細情報や、回避方法等について記していきます。
検証が困難なため、間違った情報が含まれていたり、憶測で書いている内容もあるので注意してください。

■バグの概要
　・eMMCコントローラファームのバグにより、ERASEコマンド(CMD38)が正しく処理されない
　・ERASEで指定した外の領域も破壊するため、端末が完全文鎮化するリスクが高い
　・CWMでFRやフォーマット操作を行うと、バグを誘発する

　わかりやすい解説記事をみつけました。
　-> http://pinoydroid.net/samsung-galaxy-ii-galaxy-note-mmccaperase-bug-potentially-brick-device

■復旧方法
　xdaには復旧方法のスレがあり、PITの再設定で云々…とやっていますが詳細未確認です。
　（破壊度合いにもよるのかもしれない）

■回避方法
　Linuxでは、ドライバでmmcデバイスのスペックを登録しておくことで、使える機能が選択できるようになっています。
　その中にMMC_CAP_ERASEというものがあり、これがONだとERASEコマンドに対応している（必要な場面でERASEコマンドを発行する）ということを意味します。
　逆に言うと、MMC_CAP_ERASEを外しておけばERASEコマンドに対応していないと見なされ、コマンドが発行されないため、バグが回避できます。

■stockカーネルとユーザーランドの組み合わせ
　GBの頃から、stockカーネルではMMC_CAP_ERASEがONになっていたようです。
　ところが問題が大々的に取り上げられたのはICSのアップデート時期からです。
　この理由として、GBの頃の大半のカスタムリカバリは、FRやフォーマット操作をした場合、ERASEコマンドが発行されない機構になっていたという情報があります。（前述のサイトより）
　ちなみにERASEコマンド以外の方法とは、具体的にはライト系のコマンドを代用することが考えられます。
　ところが、ICSの頃になると大半のカスタムリカバリでERASEコマンドを発行する機構に変わったため、問題が発生したようです。（前述のサイトより）
　では、GBの頃のカスタムリカバリを使っていれば大丈夫かというと、zip内のupdater-scriptの書き方によってはやはり問題が起こりうるそうです。
　（転じて、stockリカバリではERASEコマンドを発行させないようにユーザーランドを実装することで問題を完全にコントロールしていると推測できます）
　結局のところ、MMC_CAP_ERASEを外さない限り、リスクは残りうるということです。

■判定方法
　eMMCコントローラファームの情報等を拾ってバグ入りチップかどうかが判定できるアプリ
　-> http://forum.xda-developers.com/showpost.php?p=27014974&postcount=1

■MSMの固有問題
　本件の回避方法として大々的に取り上げられている実装はExynosプラットフォームに依存しているように見えます。SC-05DはMSMプラットフォームですが、MSMプラットフォームでこの問題がおこっている機種は世界的に少なく、回避実装として参考にできる情報が少ないという問題があるように思います。

■MSMのあやしいところ
　drivers/mmc/host/msm_sdcc.c: mmc->caps |= MMC_CAP_WAIT_WHILE_BUSY | MMC_CAP_ERASE;

**Comment by coosee** [comment]
お疲れ様です。
（本内容はみなさんにとってあまり有用でないかもしれませんが、自身の整理も兼ねて記させていただきます）

> SC-03D、SC-05D（SC-01D、SC-01Eも同様でしょう）も同じカーネルツリーを使っている以上同様でしょう。

なるほど、SGH-I727やSGH-T989あたりの修正方法を引っ張ってくればよいのですね。。それは是非確認してみようと思います。

これ -> https://github.com/kbc-developers/android_kernel_samsung_msm8660/commit/61b46c8f6a74ba13c99ee140024cf141b21bead4
がEntropy512さんのパッチだったので、Entropy512さんのgithubに行き、
Entropy512さんのどのツリーから引っ張ってきたのだろうという探し方をしていました。

いちおう、ここ -> https://github.com/Entropy512/n7000_erasetest_kernel/commit/c9b5be55339417831a507de9e41a0493113c8076
で同じ物が見つかったのですが、n7000_erasetest_kernelという名称だし、このツリーは違そうだなあと。
だからといって、Entropy512さんの他のツリーもExynos系っぽいしうむむ...と悩んでいました。
（よろしければパッチをどのリポジトリから引っ張ってきたか教えていただけると幸いです。）
（もしかしたらgithubにフォーク元のリポジトリを知るための機能があるのかもしれませんが、お恥ずかしいことにそういった使いこなしが全くできていません...）

そこでExynos系の直し方をMSM系に適用するとどうなるかというアプローチで解析したのが以下の内容です。

Exynos系での直し方 -> https://github.com/kbc-developers/kernel_samsung_exynos4210/commit/b241f2c85798ba4fb79058aceb5b06a223bbf2e6
はhostレイヤに手を入れるやり方で、修正しているmshci.cはCONFIG_MMC_MSHCIに依存している。

MSM系、少なくともSC-05DのconfigにはCONFIG_MMC_MSHCIがなく、これの代わりになるものはCONFIG_MMC_MSM。
で、CONFIG_MMC_MSMに依存するコードはdrivers/mmc/host/msm_sdcc.c。
その中にはMMC_CAP_ERASEを設定している場所がある。
なので、Exynos系と同じアプローチを取るなら、ここを修正するのが相応しいのではないかという推測をしました。

ところが、Entropy512さんのパッチはここではなく、coreレイヤのcore.cに手を加えている。
このコードはExynosのツリーにもあるから、この直し方でいいならExynosもcore.cをいじっていてもいいような
気がするのですが、Exynosのほうはそうしていない。なんでなのかなあと。
まぁあまり深い意味はなく、最初はmshci.cで修正して、その後他のプラットフォームに展開したときにプラットフォーム非依存な修正方法に変えただけかもしれません。
が、その辺の事情等を私が知らないこともあって、確信できていいないというのが現状です。

SGH-I727やSGH-T989あたりのツリーを追ってみたいのですが、今日は体調が悪いので明日以降にしようと思います。

**Comment by sakuramilk** [comment]
結論が書かれてたのでなにも言うことはないですが
同じ効果が得られるとは思います。

ただ対象がSDカードの場合でもMMC_CAP_ERASEを使えないことになる、
というのが差でしょうか。

**Comment by sakuramilk** [comment]
本件の対策をcommitしました。

samsungからのpatch: http://bit.ly/SrEMsb
exynos系のpatch http://bit.ly/QS5wQp

両方入れる意味はあんまないんですが念のため入れときました。
コードレビューお願いします。

問題なければ突撃します(やぁす君がw)

**Comment by sakuramilk** [comment]
Closeします
