### ISSUE TITLE
recoveryからのリブートが失敗する

### ISSUE THREAD

**Issue by sakuramilk** [kbc-developers/android_kernel_samsung_msm8660-common#6]
現象： recoveryからのreboot system, reboot recovery, reboot downloadが共に失敗する
備考：USBが刺さっているとそのままLPMに移行する

またrebootまでに10秒程度かかる

**Comment by sakuramilk** [comment]
last_kmsgで通常時のリブートとrecoveryからのリブートのログを調べてみました。

通常時のリブート
[  108.267272] mmc4: card 0002 removed
[  108.357330] disable_charging_before_reset: check voltage(4015000)
[  108.357604] Disabling non-boot CPUs ...
[  108.360626] Restarting system with command 'recovery'.  (mach-msm/restart.c:L242)
[  108.361175] set_dload_mode <0> ( c0181200 )
[  108.361541] Going down for restart now recovery
[  108.362152] PM8XXX_VERSION_8058
[  108.362518] PM8XXX_VERSION_8058_END
[  108.362854] PM8XXX_VERSION_8901
[  108.363464] 1
[  108.363769] 2
[  108.372131] PM8XXX_VERSION_8901_END

recoveryからのリブート
[  411.887420] fsa9480 5-0025: dev1: 0x0, dev2: 0x0
[  411.887481] fsa9480_usb_cb attached 0
[  411.887725] usb_do_work: usb: notify offline
[  411.888671] adb_release
[  411.888977] android_work: sent uevent USB_STATE=DISCONNECTED
[  411.889343] adb_open
[  411.889434] adb_bind_config
[  411.890899] sec-battery sec-battery: sec_bat_set_property: cable was changed(0)
[  411.895385] [TSP] calibration is on going
[  411.905181] [TSP] normal mode
[  412.052490] disable_charging_before_reset: skip charging control
[  412.052825] Disabling non-boot CPUs ...
[  412.054779] Restarting system with command 'recovery'. (mach-msm/restart.c:L242)

ログを出している箇所を調べたところmach-msm/restart.c:L242の後ログが全くでていません。
この辺りが怪しいと思われます

**Comment by ma34s** [comment]
$B%j%V!<%H$8$c$J$/$F!"%7%c%H%@%&%s$7$F$k$H!"$=$s$JF0$-$K$J$j$=$&$G$9$h$M!#(B
2012/11/21 22:58 "sakuramilk" notifications@github.com:

**Comment by ma34s** [comment]
リブートじゃなくて、シャットダウン動作になってたら、そんな動きになりそうじゃないですか？

電源OFF　→　あっ！USB刺さってる！　→LPMモードで起動

**Comment by sakuramilk** [comment]
そうなっているものと思われます。
リブート要因が書き込まれず、PowerOffと同じ状態になっているのではと推測しています。
が、一応10秒待てば再起動しますのでシャットダウンではないですね。

**Comment by sakuramilk** [comment]
本件はcooseeさんの調査によりimx6q向けの修正である以下のpatchにより
発生するようになっていることが判明しました。
http://git.kernel.org/?p=linux/kernel/git/stable/linux-stable.git;a=commit;h=faaeea39363ad54b3dfe23cc982e484f6e54aa5a

msm8660ではこのコードを入れるとうまく動作できないようです。
これを削除することで解決します。
